- name: kube test
  connection: kubernetes
  hosts: all
  gather_facts: True
  tasks:
    #    - name: raw_module
    #  raw: date

    - name: debug
      debug:
        msg: "{{ hostvars[inventory_hostname] }}"

    - name: command_module
      command: "echo hello"
