apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: ansible-kube-connect-test
  name: web
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ansible-kube-connect-test
    deploymentconfig: ansible-kube-connect-test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
